import { useEffect, useMemo, useState } from "react";

import type {
  CsvFileMetadata,
  KickFromCsvFileResult,
  KickFromCsvResponse,
} from "../models/types";
import { fetchCsvFiles } from "../services/csvFiles";
import { kickFromCsv } from "../services/kickFromCsv";
import { cancelKickJob } from "../services/cancelKick";

export const KickFromCsvPanel = () => {
  const [files, setFiles] = useState<CsvFileMetadata[]>([]);
  const [selectedMap, setSelectedMap] = useState<Record<string, boolean>>({});
  const [dryRun, setDryRun] = useState(true);
  const [kicking, setKicking] = useState(false);
  const [statusMessage, setStatusMessage] = useState<string | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [results, setResults] = useState<KickFromCsvFileResult[] | null>(null);
  const [cancelling, setCancelling] = useState(false);

  const selectedFilenames = useMemo(
    () =>
      files
        .filter((file) => selectedMap[file.filename])
        .map((file) => file.filename),
    [files, selectedMap]
  );

  useEffect(() => {
    void refresh();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const refresh = async () => {
    try {
      const fetched = await fetchCsvFiles();
      setFiles(fetched);
      setSelectedMap((prev) => {
        const next: Record<string, boolean> = {};
        fetched.forEach((file) => {
          if (prev[file.filename]) {
            next[file.filename] = true;
          }
        });
        return next;
      });
    } catch (error) {
      setErrorMessage((error as Error).message);
    }
  };

  const toggleSelection = (filename: string) => {
    setSelectedMap((prev) => ({
      ...prev,
      [filename]: !prev[filename],
    }));
  };

  const handleKick = async () => {
    if (selectedFilenames.length === 0 || kicking) {
      setErrorMessage("Select at least one CSV file to continue.");
      return;
    }

    setKicking(true);
    setErrorMessage(null);
    setStatusMessage(null);
    setResults(null);

    try {
      const response: KickFromCsvResponse = await kickFromCsv({
        filenames: selectedFilenames,
        dryRun,
      });
      setStatusMessage(response.message);
      setResults(response.results);
      await refresh();
    } catch (error) {
      const message = (error as Error).message;
      if (message.toLowerCase().includes("cancel")) {
        setStatusMessage(message);
        setErrorMessage(null);
      } else {
        setErrorMessage(message);
      }
      setResults(null);
    } finally {
      setKicking(false);
      setCancelling(false);
    }
  };

  const handleCancel = async () => {
    if (!kicking || cancelling) {
      return;
    }
    setCancelling(true);
    try {
      await cancelKickJob();
      setStatusMessage("Kick cancellation requested.");
      setErrorMessage(null);
    } catch (error) {
      setErrorMessage((error as Error).message);
    } finally {
      setCancelling(false);
    }
  };

  return (
    <section className="kick-panel">
      <div className="kick-panel__header">
        <div>
          <h2>Kick from CSV</h2>
          <p>
            Select one or more CSV exports generated by the scanner and remove
            the matching members from the guild.
          </p>
        </div>
        <button
          type="button"
          className="secondary-button"
          onClick={refresh}
          disabled={kicking}
        >
          Refresh list
        </button>
      </div>

      <div className="kick-panel__content">
        <div className="csv-list">
          {files.length === 0 ? (
            <p className="csv-list__empty">
              No CSV exports found in the csv/ directory.
            </p>
          ) : (
            <ul>
              {files.map((file) => (
                <li key={file.filename} className="csv-item">
                  <label>
                    <input
                      type="checkbox"
                      checked={Boolean(selectedMap[file.filename])}
                      onChange={() => toggleSelection(file.filename)}
                      disabled={kicking}
                    />
                    <span>
                      <strong>{file.filename}</strong>
                      <small>
                        {file.rowCount} users ·{" "}
                        {new Date(file.modifiedAt).toLocaleString(undefined, {
                          dateStyle: "medium",
                          timeStyle: "short",
                        })}
                      </small>
                    </span>
                  </label>
                </li>
              ))}
            </ul>
          )}
        </div>

        <div className="kick-panel__actions">
          <label className="dry-run-toggle">
            <input
              type="checkbox"
              checked={dryRun}
              onChange={(event) => setDryRun(event.target.checked)}
              disabled={kicking}
            />
            <span>Dry run (report only, no kicks)</span>
          </label>
          <button
            type="button"
            disabled={kicking || selectedFilenames.length === 0}
            onClick={handleKick}
            className="kick-button"
          >
            {kicking
              ? "Processing…"
              : dryRun
              ? "Dry run selected CSVs"
              : "Kick selected users"}
          </button>
          {kicking && (
            <button
              type="button"
              className="secondary-button secondary-button--danger"
              onClick={handleCancel}
              disabled={cancelling}
            >
              {cancelling ? "Cancelling…" : "Cancel kick job"}
            </button>
          )}
          <p className="kick-panel__hint">
            {selectedFilenames.length === 0
              ? "Select at least one CSV."
              : `${selectedFilenames.length} file${
                  selectedFilenames.length === 1 ? "" : "s"
                } selected.`}
          </p>
        </div>
      </div>

      <div className="feedback">
        {statusMessage && <p className="status success">{statusMessage}</p>}
        {errorMessage && <p className="status error">{errorMessage}</p>}
      </div>

      {results && results.length > 0 && (
        <div className="kick-results">
          {results.map((file) => (
            <article key={file.filename} className="kick-result-card">
              <header>
                <h3>{file.filename}</h3>
                <span className="badge">
                  {file.dryRun ? "Dry run" : "Live kick"}
                </span>
              </header>
              <ul>
                <li>
                  Total rows: <strong>{file.totalRows}</strong>
                </li>
                <li>
                  Matched members: <strong>{file.matchedUsers}</strong>
                </li>
                <li>
                  Successful kicks: <strong>{file.successfulKicks}</strong>
                </li>
              </ul>
              {file.failures.length > 0 && (
                <details>
                  <summary>{file.failures.length} issue(s) encountered</summary>
                  <ul>
                    {file.failures.map((failure, index) => (
                      <li key={`${file.filename}-failure-${index}`}>
                        {failure}
                      </li>
                    ))}
                  </ul>
                </details>
              )}
            </article>
          ))}
        </div>
      )}
    </section>
  );
};
